<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>java-wasm-cesar</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <teavm.version>0.15.0</teavm.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-classlib</artifactId>
            <version>${teavm.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.teavm</groupId>
            <artifactId>teavm-jso-apis</artifactId>
            <version>${teavm.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.teavm</groupId>
                <artifactId>teavm-maven-plugin</artifactId>
                <version>${teavm.version}</version>
                <executions>
                    <execution>
                        <id>wasm</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <targetType>WEBASSEMBLY_GC</targetType>
                            <mainClass>java_cesar.Main</mainClass>
                            <targetDirectory>${project.build.directory}/wasm-gc</targetDirectory>
                            <optimizationLevel>ADVANCED</optimizationLevel>
                            <minifying>true</minifying>
                            <debugInformationGenerated>false</debugInformationGenerated>
                            <sourceMapsGenerated>false</sourceMapsGenerated>
                            <sourceFilesCopied>false</sourceFilesCopied>
                        </configuration>
                    </execution>
                    <execution>
                        <id>wasm-runtime</id>
                        <goals>
                            <goal>copy-webassembly-gc-runtime</goal>
                        </goals>
                        <configuration>
                            <targetDirectory>${project.build.directory}/wasm-gc</targetDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>